version: '3'

services:

  # Vue.js app
  app:
    image: node:8
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    ports:
      - 80:3000
    command: bash -c "npm install && npm start"
    depends_on:
      - api
    restart: on-failure
    environment:
      WDS_PORT: 3000
      WDS_PUBLIC_SOCKET: localhost:80
      WDS_PROXY_TARGET: http://api:3000
  
  # REST API
  api:
    image: node:8
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./api:/home/node/app
    ports:
      - 8080:3000
    command: bash -c "npm install && npm start"
    depends_on:
      - mongo
    restart: on-failure
    environment:
      PORT: 3000
      MONGO_HOST: mongo
      MONGO_DATABASE: App
      
  # MongoDB database
  mongo:
    image: mongo
    volumes:
      - /data/db
    restart: on-failure
