version: '3'

services:
  app:
    image: node:8
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    ports:
      - 80:3000
    command: bash -c "npm install && npm start"
    depends_on:
      - api
    environment:
      WDS_PORT: 3000
      WDS_PUBLIC_SOCKET: localhost:80
      WDS_PROXY_TARGET: http://api:3000
  
  api:
    image: node:8
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./api:/home/node/app
    ports:
      - 8080:3000
    command: bash -c "npm install && npm start"
    depends_on:
      - mongo
    environment:
      PORT: 3000
  # app:
  #   container_name : app
  #   restart : always
  #   build : .  # specify the directory of the Dockerfile
  #   ports : #specify ports forwarding
  #     - "80:80" 
  #     - "8080:8080"
  #   volumes : # mount points
  #     - ./api:/var/www/api
  #     - ./app:/var/www/app
  #   links :
  #     - mongo # link this service to the database service
  #   depends_on :
  #     - mongo
      
  mongo : # database
    container_name : mongo
    image : mongo
    volumes :
      - ./data:/data/db
    ports :
      - "27017:27017"

  mongo-express : # mongodb web managment ui
    container_name : mongo-express
    image : mongo-express 
    links : # link this service to the database service
      - mongo:mongo
    ports :
      - "8081:8081"
    restart : always
    command : sh -c 'sleep 10 && tini -- node app'
