version: '3'

services:
  app:
    image: node:8
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    ports:
      - 80:3000
    command: bash -c "npm install && npm start"
    depends_on:
      - api
    environment:
      WDS_PORT: 3000
      WDS_PUBLIC_SOCKET: localhost:80
      WDS_PROXY_TARGET: http://api:3000
  
  api:
    image: node:8
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./api:/home/node/app
    ports:
      - 8080:3000
    command: bash -c "npm install && npm start"
    depends_on:
      - mongo
    environment:
      PORT: 3000
      MONGO_HOST: mongo
      MONGO_DATABASE: App
      
  # MongoDB database
  mongo:
    image: mongo
    volumes:
      - /data/db

  # mongodb web managment ui
  # TODO: Remove this before submission.
  mongo-express: 
    image: mongo-express 
    links:
      - mongo:mongo
    ports :
      - "8081:8081"
    restart : always
    command : sh -c 'sleep 10 && tini -- node app'
