# users_test.yaml

test_name: Check /users endpoint

includes:
  - !include includes.yaml

stages:
  - name: Creating a new random user with a random password
    request:
      url: "{api_uri:s}" + /users/register
      method: POST
      json: 
        username: AzureDiamond
        password: hunter2
        fullname: Joey Pardella 
        age: 15    
    response:
      headers:
        content-type: application/json
      status_code: 201
      body:
        status: true

  - name: Creating an existing user
    request:
      url: "{api_uri:s}" + /users/register
      method: POST
      json: 
        username: AzureDiamond
        password: hunter2
        fullname: Joey Pardella 
        age: 15    
    response:
      headers:
        content-type: application/json
      status_code: 200
      body:
        status: false
        error: User already exists!
        
        